### ISSUE TITLE
Favicons

### ISSUE THREAD

**Issue by halfempty** [everythingtype/kaufman#1]
@gehalber Traditional first issue!

Have a design for the favicon?

**Comment by gehalber** [comment]
I think you'll appreciate this...
there should be all of the sizes you need baked into the ico file.
https://www.dropbox.com/s/0gs8ymyl0lec1uw/favicon.ico?dl=0

**Comment by halfempty** [comment]
@gehalber It's so heavy metal!!!

Actually, I need some larger sizes for iOS etc. Do we have a vector?

**Comment by gehalber** [comment]
Ha! Dead Kennedys.
Do you know the dimensions?

**Comment by halfempty** [comment]
@gehalber It gets more out-of-hand each year:

192px
180px
152px
144px
120px
114px
76px
72px
57

And vector SVG if we can, for Safari's "pinned tabs"

**Comment by philipdibello** [comment]
@halfempty Hey Marty! I found a [generator](https://realfavicongenerator.net) that automates the export process and generates image files and code. I exported a package of two different ways to go about integrating favicons. One generated a bunch of file sizes and types, the other is slimmed down version.

If this doesn't work or if it would be more helpful just as the sizes you've mentioned earlier I can sort those out for you as well.

[favicons large.zip](https://github.com/everythingtype/kaufman/files/598463/favicons.large.zip)

[favicons small.zip](https://github.com/everythingtype/kaufman/files/598462/favicons.small.zip)

**Comment by halfempty** [comment]
@philipdibello Thanks! The package needs to be tweaked a bit, from how it comes. But it wouldn't be right to spend too much time on this small issue-- we've got more than what we need for this site -- so we'll pick up this conversation on the next site. Cheers
