### ISSUE TITLE
Hot areas on image to advance / receed

### ISSUE THREAD

**Issue by halfempty** [everythingtype/kaufman#12]
**Dean says:**

[desktop] is it possible that, additionally, clicking on the right or left of the image could progress or return the image?

[mobile] is it possible that swiping or touching would progress/return the images?  Particularly hard and counter intuitive on mobile gui to hit those little arrows

**Comment by halfempty** [comment]
@gehalber The desktop part sounds good.

For mobile... 
Swiping is difficult. It would require some research on my part. (The last time I looked into it it was a rabbit hole, though the situation may have improved.)

What I would suggest, 'cause it would be simple and also possibly good in its own right, is simply tapping the image to advance. And forgoing a larger "back" button.

**Comment by gehalber** [comment]
There's also something strange about swiping and the image fading. Its not what you expect would happen. I think tapping and advancing seems like a nice idea. I'll check in with him first before proceeding.

**Comment by gehalber** [comment]
If we go with the tapping to advance, is it worth, or even possible, to go backward if you click on the left side of the image. I'm not sure a user would really know what to do unless we gave them directions, but asking if that's simple or difficult.

**Comment by gehalber** [comment]
And also! your opinion...

**Comment by halfempty** [comment]
Done
