### ISSUE TITLE
White Space

### ISSUE THREAD

**Issue by halfempty** [everythingtype/kaufman#13]
**Dean says:**

I love seeing the main images so large after years on the small end. Also love how the image is scaling to screen/window size.

Feeling, however, i want to have a bit more white space on the page. Measured and suggesting the large images be at 95% of current size.

**Comment by halfempty** [comment]
@gehalber Ok yes... I've achieved the 5% reduction by increasing the padding below the image by 33px. Better?

**Comment by gehalber** [comment]
Nice!
