### ISSUE TITLE
Fade Out

### ISSUE THREAD

**Issue by halfempty** [everythingtype/kaufman#14]
**Dean says:**

I see this currently happening on overview.  Will it ultimately happen on ALL pages including 'splash page'?

**Comment by halfempty** [comment]
@gehalber Yes, we can add the fade-out to other pages. 

What fades? The top and side nav bars? Or all text?

**Comment by gehalber** [comment]
Let me ask what he'd like to do since I think he often thinks of the caption text on the homepage as part of the image, in a way.

**Comment by gehalber** [comment]
So fade out navigation on all pages of the site that features a large image. On the homepage, the image and the caption should remain. Make sense?

**Comment by halfempty** [comment]
@gehalber To be really specific...

Fade on:
- individual "portfolio" template
- the portfolios grid page 
- homepage

Do not fade on:
- News
- Profile
- Contact

?

**Comment by gehalber** [comment]
Great.

**Comment by halfempty** [comment]
Done
