### ISSUE TITLE
Keyboard commands

### ISSUE THREAD

**Issue by gehalber** [everythingtype/kaufman#15]
Dean says he's having an issue with the keyboard forward/backward. That is, images are progressing when you click on left arrow. And going backward when clicking on right arrow. Weird. I'm not experiencing that on chrome. are you? He says safari and firefox are doing that for him

**Comment by halfempty** [comment]
@gehalber This is working properly for me in all browsers (??)

**Comment by halfempty** [comment]
@gehalber Oh wait... he was right, I had it backwards. Updated.
