### ISSUE TITLE
News Image Display

### ISSUE THREAD

**Issue by gehalber** [everythingtype/kaufman#19]
@halfempty 
At the moment, if you only have one image in a news item, it stays as a thumbnail in the grid, but it should probably expand the full width.

See here: http://kaufman.etc-nyc.com/86-2/

![screen shot 2017-03-20 at 11 05 28 pm](https://cloud.githubusercontent.com/assets/6076488/24130902/c560c822-0dc1-11e7-86d6-0536f1d1f31e.png)

**Comment by halfempty** [comment]
Fixed, done
