### ISSUE TITLE
Webfonts

### ISSUE THREAD

**Issue by halfempty** [everythingtype/kaufman#2]
@gehalber Do we have webfonts for Comb Pro?

**Comment by gehalber** [comment]
We need to purchase it, but just want to make sure that if I send you the woff files you can embed them. Right?

**Comment by gehalber** [comment]
Just purchased and placed in your folder.

**Comment by halfempty** [comment]
@gehalber Are we using the "Forms" font anywhere?

**Comment by gehalber** [comment]
We’re not. It came with the package.
