### ISSUE TITLE
Mobile horizontal

### ISSUE THREAD

**Issue by gehalber** [everythingtype/kaufman#21]
@halfempty 
We may need to make mobile conditioning formatting. On the horizontal mobile, the image is pretty small. Can we increase the size/proportion in these smaller formats?

![screen shot 2017-03-20 at 11 43 33 pm](https://cloud.githubusercontent.com/assets/6076488/24131853/78e21f68-0dc7-11e7-8458-72ff1e906bff.png)

**Comment by halfempty** [comment]
@gehalber I was able to make it slightly bigger. Making it much bigger means big changes.
