### ISSUE TITLE
ABOUT PAGE column layout adjustment

### ISSUE THREAD

**Issue by keningzhu** [everythingtype/kaufman#25]
- [x] Commercial Commissions - two columns
- [x] Editorial Commissions - two columns
- [x] Cultural Commissions - one column
- [x] Book Contributions - one column

@halfempty

**Comment by gehalber** [comment]
@halfempty 
Ok, discussed with Dean about this and edited the above. Can you tweak?

**Comment by halfempty** [comment]
@gehalber When you say two columns-- do you mean that, say, the "Editorial" content should itself be presented in two columns? Or do you mean that "Editorial" should be on the left and "Cultural" should be on the right?

**Comment by halfempty** [comment]
@gehalber I've put it in as the columns-within-sections, 'cause the CSS for that is easiest. But let me know if you want it the other way

http://kaufman.etc-nyc.com/profile/

**Comment by gehalber** [comment]
That's perfect. Thanks.
