### ISSUE TITLE
Cursor arrows

### ISSUE THREAD

**Issue by halfempty** [everythingtype/kaufman#27]
- [ ] Put arrow on cursor when on top of image - to indicate click to advance or return

**Comment by halfempty** [comment]
@keningzhu I don't think I understand this point-- on the slideshows, we've already set the cursor to pointer. Is there another place, which we're missing?

**Comment by gehalber** [comment]
@halfempty 
I think Dean is asking for the trick where we turn the cursor into an arrow. And if we're on the right side of image carousel goes forward, and if we're on the left side of image carousel goes back.

What do you think?

**Comment by halfempty** [comment]
@gehalber @keningzhu This is similar to issue #12, which I see we left somewhat unresolved. 

Per that discussion, I'll add the left-side/right-side thing on desktop. On mobile we'll leave it tap-anywhere-to-advance.

Do you have specific arrows that you'd like me to use?

**Comment by gehalber** [comment]
@halfempty 
Let's just use the arrows that we have in the bottom right corner, but make them black.

**Comment by halfempty** [comment]
@gehalber Okay, this is done
