### ISSUE TITLE
Portfolio Template

### ISSUE THREAD

**Issue by halfempty** [everythingtype/kaufman#6]
@gehalber I've begun on the main Portfolio template. It's just the beginning, still, though it does display images. More to come.

http://kaufman.etc-nyc.com/portfolio/overview/

**Comment by gehalber** [comment]
Cool, though this will become a carousel eventually, right?

**Comment by halfempty** [comment]
@gehalber Okay, spot of progress here...

http://kaufman.etc-nyc.com/portfolio/overview/

I've done the carousel as a simple show/hide, rather than any sliding or fading. Is this the approach you're looking for?

**Comment by gehalber** [comment]
We had envisioned a nice graceful fade in/fade out. Thanks!

**Comment by halfempty** [comment]
@gehalber Updated to a fade:

http://kaufman.etc-nyc.com/portfolio/overview/

**Comment by gehalber** [comment]
Cool. Can you slow down a little bit more?
It should feel like a slow meditative switch from image to another. Like if you were in a large, white room with floor to ceiling windows looking out on a meadow and you had all the time in the world...that speed.

**Comment by gehalber** [comment]
I like it!
