### ISSUE TITLE
News section

### ISSUE THREAD

**Issue by halfempty** [everythingtype/kaufman#7]
@gehalber Some progress here...

http://kaufman.etc-nyc.com/category/news/

With the exception of the styling of the image lightbox (the lightbox works, but the style is default), I *think* everything for this section is in.

Take a look?

**Comment by halfempty** [comment]
@gehalber Okay, lightbox styles are in

http://kaufman.etc-nyc.com/category/news/

**Comment by gehalber** [comment]
Beautiful. Can you remove the underlines in the Share links. I think its obvious they're links without. Thanks.

**Comment by halfempty** [comment]
OK, underlines removed

**Comment by gehalber** [comment]
wait, it looks like they're still there...

**Comment by halfempty** [comment]
@gehalber Cache issue, I think. Gonna go ahead and close this one...
