### ISSUE TITLE
Navigation timed vanish

### ISSUE THREAD

**Issue by gehalber** [everythingtype/kaufman#8]
The other feature we wanted, which we may or may not have discussed, is that we want the navigation to fade away if there's been no cursor movement for an extended period of time. Maybe like 5 seconds or 10 seconds?

**Comment by halfempty** [comment]
@gehalber Yeah! Okay updated...

http://kaufman.etc-nyc.com/portfolio/overview/

Transition between slides: 2 seconds

Navigation fade:
- After 5 idle seconds, fade will commence
- Fade will take 5 seconds to complete
- On mouse-move, navigation will take .5 seconds to fade back in

Generally the idea? Tweak the timing?

(Still need to test this on touch-based devices.)

**Comment by gehalber** [comment]
NICE!
