### ISSUE TITLE
Captions

### ISSUE THREAD

**Issue by halfempty** [everythingtype/kaufman#9]

**Comment by halfempty** [comment]
@gehalber Okay, progress on captions...

- I have them showing/hiding, rather than cross fading. What do you think? Would you rather they crossfade?
- On the phone size, the mockups show them appearing directly under the image, rather than pinned near the controls. I did this because it is easier from a dev point of view. But if you feel that it would be better to have them move up, I can do that.

**Comment by gehalber** [comment]
I do think it would be nice if those captions cross faded too.

I think its ok for the captions to be pinned actually on mobile. Can't remember why we did it the other way. Thanks!

**Comment by halfempty** [comment]
Done
